# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YelpApi' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for YelpApi
pod 'Alamofire', '~> 5.5'
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'Kingfisher', '~> 7.0'

  target 'YelpApiTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'MockingbirdFramework'
  end

  target 'YelpApiUITests' do
    # Pods for testing
  end

end
